set-option -g default-terminal 'screen-256color'
set -g prefix ^A
set -g status-position top   
set-option -sa terminal-overrides ",xterm*:Tc"
set -g base-index 1  
set -g renumber-windows on
set -g detach-on-destroy off

set -g @catppuccin_flavour 'frappe'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'dreamsofcode-io/catppuccin-tmux'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @continuum-restore 'on'
set -g @resurrect-strategy-nvim 'session' 
set -g @resurrect-capture-pane-contents 'on'

bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

set -g mouse on
set-window-option -g mode-keys vi


bind-key -r f run-shell "tmux neww ~/bin/tmux-sessionizer"

bind-key -T copy-mode-vi 'v' send -X begin-selection

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"


setenv -g TMUX_PLUGIN_MANAGER_PATH "$HOME/.config/tmux/plugins/"


if "test ! -d ~/.config/tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm && ~/.config/tmux/plugins/tpm/bin/install_plugins'"

run -b '~/.config/tmux/plugins/tpm/tpm'
