---
- name: Install dependencies
  ansible.builtin.package:
    name:
      - ripgrep
      - fd
      - npm
    state: latest
  become: yes

- name: Set sudo
  ansible.builtin.replace:
    path: "/etc/sudoers.d/10-installer"
    regexp: '\%wheel ALL=\(ALL\) ALL'
    replace: "%wheel ALL=(ALL) NOPASSWD: ALL"
  become: yes

- name: Create Symlink for snap classic
  file:
    src: /var/lib/snapd/snap
    dest: /snap
    state: link
  become: yes

- name: Install emoji font
  kewlfft.aur.aur:
    use: yay
    name:
      - ttf-twemoji

